-- Part 2: Triggers for auto-increment
CREATE OR REPLACE TRIGGER trg_roles BEFORE INSERT ON roles FOR EACH ROW
BEGIN SELECT seq_roles.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_users BEFORE INSERT ON users FOR EACH ROW
BEGIN SELECT seq_users.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_user_tokens BEFORE INSERT ON user_tokens FOR EACH ROW
BEGIN SELECT seq_user_tokens.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_customers BEFORE INSERT ON customers FOR EACH ROW
BEGIN SELECT seq_customers.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_interactions BEFORE INSERT ON customer_interactions FOR EACH ROW
BEGIN SELECT seq_interactions.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_categories BEFORE INSERT ON customer_categories FOR EACH ROW
BEGIN SELECT seq_categories.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_leads BEFORE INSERT ON leads FOR EACH ROW
BEGIN SELECT seq_leads.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_lead_scores BEFORE INSERT ON lead_scores FOR EACH ROW
BEGIN SELECT seq_lead_scores.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_lead_assign BEFORE INSERT ON lead_assignments FOR EACH ROW
BEGIN SELECT seq_lead_assign.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_tasks BEFORE INSERT ON tasks FOR EACH ROW
BEGIN SELECT seq_tasks.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_task_assign BEFORE INSERT ON task_assignments FOR EACH ROW
BEGIN SELECT seq_task_assign.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_analytics BEFORE INSERT ON analytics_reports FOR EACH ROW
BEGIN SELECT seq_analytics.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_sales_rep BEFORE INSERT ON sales_reports FOR EACH ROW
BEGIN SELECT seq_sales_rep.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_cust_rep BEFORE INSERT ON customer_reports FOR EACH ROW
BEGIN SELECT seq_cust_rep.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_behavior BEFORE INSERT ON customer_behavior FOR EACH ROW
BEGIN SELECT seq_behavior.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_recs BEFORE INSERT ON recommendations FOR EACH ROW
BEGIN SELECT seq_recs.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_notifs BEFORE INSERT ON notifications FOR EACH ROW
BEGIN SELECT seq_notifs.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_reminders BEFORE INSERT ON reminder_logs FOR EACH ROW
BEGIN SELECT seq_reminders.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_social BEFORE INSERT ON social_sources FOR EACH ROW
BEGIN SELECT seq_social.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_campaigns BEFORE INSERT ON campaign_reports FOR EACH ROW
BEGIN SELECT seq_campaigns.NEXTVAL INTO :NEW.id FROM DUAL; END;
/
CREATE OR REPLACE TRIGGER trg_revenue BEFORE INSERT ON revenue_reports FOR EACH ROW
BEGIN SELECT seq_revenue.NEXTVAL INTO :NEW.id FROM DUAL; END;
/

-- Indexes
CREATE INDEX idx_users_email      ON users(email);
CREATE INDEX idx_customers_email  ON customers(email);
CREATE INDEX idx_customers_status ON customers(status);
CREATE INDEX idx_leads_status     ON leads(status);
CREATE INDEX idx_tasks_status     ON tasks(status);
CREATE INDEX idx_notifs_user      ON notifications(user_id);
CREATE INDEX idx_social_platform  ON social_sources(platform);
